# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: abde17fce2a38b4aadb2897c5228cbe19da8b70de3e2015f556c29dece02ef99cefa3e09395e0db6008d9e2f8d5dca6ec8efbc34dabb67b5a6b88474ca34e4af

test:
  secret_key_base: 45e111df68362cd0e2f2d8895302ce63c0c0b3ae5bc7ca6829dc1c7d7c4819b7a7aeefd1f14137534558660435eeb2470ce00a18fa6e7dd845bea427d3e0ad7c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
